extends Node2D

var dialogue_2 = [
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "Otra vez en este lugar...",
	},
	{
		"Name": "Niño",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "¿Hola? ¿Holaa?",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "",
		"Choices": ["", ""],
		"Text": "Dios, que susto.",
	},
	{
		"Name": "Niño",
		"Expression": "Neutral",
		"Position": "",
		"Choices": ["", ""],
		"Text": "¿Sabes dónde está mi madre?",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "¿Tu madre?",
	},
	{
		"Name": "Niño",
		"Expression": "Neutral",
		"Position": "",
		"Choices": ["", ""],
		"Text": "Estábamos cruzando la calle para ir al parque y...no sé, pero...",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "¿Pero?...",
	},
	{
		"Name": "Niño",
		"Expression": "Neutral",
		"Position": "",
		"Choices": ["", ""],
		"Text": "No sé. Abrí los ojos y estaba en este lugar oscuro. Todo es raro.",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "Yo tampoco sé cómo llegué aquí... hace menos de un segundo estaba...",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "...",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "¿Dónde estaba?, ¿Por qué no lo recuerdo?",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "¿POR QUÉ MIERDA NO LO RECUERDO?",
	},
	{
		"Name": "Niño",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "...Sácame de aquí, por favor, estoy asustado.",
	},
	{
		"Name": " ",
		"Expression": "Neutral",
		"Position": "1",
		"Choices": ["", ""],
		"Text": "Yo... yo...",
	},
	]
